/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.lallorona.ui;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
import mx.itson.lallorona.entities.AccountHolder;
import mx.itson.lallorona.entities.BankStatement;
import mx.itson.lallorona.entities.Transaction;
import mx.itson.lallorona.enums.TransactionType;

/**
 *
 * @author Vanni
 */
public class AccountUi1 extends javax.swing.JFrame {

    /**
     * Creates new form AccountUi1
     */
    public AccountUi1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jplRed = new javax.swing.JPanel();
        btnSelectJson = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        jplWhite = new javax.swing.JPanel();
        lblBank = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblAccountnumber = new javax.swing.JLabel();
        lblcurrency = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAccounHolder = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        lblBarCode = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        lblInteres = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jplRed.setBackground(new java.awt.Color(204, 0, 0));
        jplRed.setForeground(new java.awt.Color(204, 0, 0));

        btnSelectJson.setBackground(new java.awt.Color(204, 0, 0));
        btnSelectJson.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSelectJson.setForeground(new java.awt.Color(255, 255, 255));
        btnSelectJson.setText("Selecciona el JSON");
        btnSelectJson.setContentAreaFilled(false);
        btnSelectJson.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSelectJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectJsonActionPerformed(evt);
            }
        });

        btnClean.setBackground(new java.awt.Color(204, 0, 0));
        btnClean.setForeground(new java.awt.Color(255, 255, 255));
        btnClean.setText("Clean");
        btnClean.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplRedLayout = new javax.swing.GroupLayout(jplRed);
        jplRed.setLayout(jplRedLayout);
        jplRedLayout.setHorizontalGroup(
            jplRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSelectJson, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplRedLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jplRedLayout.setVerticalGroup(
            jplRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplRedLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnSelectJson, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jplWhite.setBackground(new java.awt.Color(255, 255, 255));

        lblBank.setFont(new java.awt.Font("Times New Roman", 1, 45)); // NOI18N
        lblBank.setForeground(new java.awt.Color(204, 0, 0));
        lblBank.setText("HSBC");

        lblProduct.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblProduct.setForeground(new java.awt.Color(51, 51, 51));
        lblProduct.setText("BANK STATEMENT");

        lblAccountnumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAccountnumber.setForeground(new java.awt.Color(51, 51, 51));
        lblAccountnumber.setText("Account Holder:");

        lblcurrency.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblcurrency.setForeground(new java.awt.Color(51, 51, 51));
        lblcurrency.setText("$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        tblTransactions.setBackground(new java.awt.Color(255, 255, 255));
        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Descripcion", "Reference", "Amount", "Type", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTransactions.setSelectionBackground(new java.awt.Color(204, 0, 0));
        jScrollPane2.setViewportView(tblTransactions);

        tblAccounHolder.setBackground(new java.awt.Color(255, 255, 255));
        tblAccounHolder.setForeground(new java.awt.Color(51, 51, 51));
        tblAccounHolder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account Holder"
            }
        ));
        tblAccounHolder.setSelectionBackground(new java.awt.Color(153, 0, 0));
        jScrollPane4.setViewportView(tblAccounHolder);

        jPanel4.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        lblBarCode.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblBarCode.setForeground(new java.awt.Color(0, 0, 0));

        lblCode.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCode.setForeground(new java.awt.Color(51, 51, 51));

        lblInteres.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jplWhiteLayout = new javax.swing.GroupLayout(jplWhite);
        jplWhite.setLayout(jplWhiteLayout);
        jplWhiteLayout.setHorizontalGroup(
            jplWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplWhiteLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jplWhiteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplWhiteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(lblBank, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jplWhiteLayout.createSequentialGroup()
                        .addGroup(jplWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jplWhiteLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jplWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jplWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jplWhiteLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jplWhiteLayout.createSequentialGroup()
                                .addComponent(lblInteres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addContainerGap())
                    .addGroup(jplWhiteLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))))
        );
        jplWhiteLayout.setVerticalGroup(
            jplWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplWhiteLayout.createSequentialGroup()
                .addGroup(jplWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBank, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jplWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplWhiteLayout.createSequentialGroup()
                        .addComponent(lblAccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblcurrency))
                    .addGroup(jplWhiteLayout.createSequentialGroup()
                        .addComponent(lblBarCode, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCode)))
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jplWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblInteres, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jplRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jplWhite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplRed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jplWhite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectJsonActionPerformed
        //El lo que paso el profe 
        FileDialog fileDialog = new FileDialog(this, "Select json file", FileDialog.LOAD);
        fileDialog.setVisible(true);
        
        String directory = fileDialog.getDirectory();
        String filename = fileDialog.getFile();
        
        if(filename != null){
            File selectedFile = new File(directory, filename);
        try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
            StringBuilder content = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                content.append(line).append("\n");
                }
            // Convert the content to a String
            String contenido = content.toString();
            // Deserialize JSON content into a BankStatement object
            BankStatement a = BankStatement.deserialized(contenido);
            // Get the account holder details
            AccountHolder h = a.getAccountHolder();
            
            //Bar-Code
            lblBarCode.setText("||| ||||| |||| |||||||");
            
            // Generate a random number to display as the code
            Random rand = new Random();
            long randomNum = rand.nextInt(1000000000)+1;
            lblCode.setText("Code: " +randomNum);
            // Set product, account number and currency labels
            lblProduct.setText(a.getProduct());
            lblAccountnumber.setText("Account Number: " + a.getAccountNumber());
            lblcurrency.setText("Currency: " + a.getCurrency());
            lblInteres.setText("Ha ocurrido un error con el cálculo de nuestra tasa de intereses.\n" +
                "Recuerda que es del 3%.\n" +
                "Consulta de forma presencial.");
            // Add account holder info to the tblAccounHolder table
            DefaultTableModel m =(DefaultTableModel) tblAccounHolder.getModel();
            m.addRow(new Object[]{ "Code: " +           h.getCode() });
            m.addRow(new Object[]{ "Name: " +           h.getName() });
            m.addRow(new Object[]{ "Adress: " +        h.getAddress() });
            m.addRow(new Object[]{ "City: " +           h.getCity() });
            m.addRow(new Object[]{ "Taxpayer-id: " +              h.getTaxpayerId() });
            m.addRow(new Object[]{ "Zip code: "  +   h.getZipCode() });
            
            // Define the transaction type to filter (Expenses)
            TransactionType l = TransactionType.EXPENSE;
            // Initialize total balance for calculations
            float totalbalance = (float) 50000.000;
            // Clear the transactions table before filling it
            DefaultTableModel model =(DefaultTableModel) tblTransactions.getModel();
            model.setRowCount(0);
            // Get the list of transactions and sort them by date
            List<Transaction> txs = new ArrayList<>( a.getTransactions() );
            txs.sort( Comparator.comparing(Transaction::getDate) );
            // Define the date format for displaying transaction dates
            SimpleDateFormat dateFormat= new SimpleDateFormat("dd'/'MM'/'yyyy");
            // Loop through transactions to calculate running balance and display them
            for (Transaction t : txs) {
            if (t.getType() == l ){
                 // If transaction is an expense, subtract amount from total balance
                totalbalance -= t.getAmount();
                t.setBalance(totalbalance);
            }else{
                // If transaction is income, add amount to total balance
                
                totalbalance += t.getAmount();
                t.setBalance(totalbalance);
            }
           // Add transaction data as a new row in the transactions table
            model.addRow(new Object[]{
                 dateFormat.format(t.getDate()),
                 t.getDescription(),
                 t.getReference(),
                 "$" + t.getAmount(),
                 t.getType(),
                 t.getBalance()
                 
                            });                  
        }
 }
        catch (IOException ex) {
            // Handle and print any IOException during file reading
                      System.out.println("Error: " + ex.getMessage());
                    }
        
    }      }//GEN-LAST:event_btnSelectJsonActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        //It is responsible for cleaning the previous JSON
        lblBarCode.setText(""); 
        lblCode.setText("Code: ");
        lblProduct.setText("BANK STATEMENT");
        lblAccountnumber.setText("Account Number: ");
        lblcurrency.setText("Currency: ");
         lblInteres.setText(" ");
    
        ((DefaultTableModel)tblAccounHolder.getModel()).setRowCount(0);
        ((DefaultTableModel)tblTransactions.getModel()).setRowCount(0);
            }//GEN-LAST:event_btnCleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountUi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountUi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountUi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountUi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountUi1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnSelectJson;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel jplRed;
    private javax.swing.JPanel jplWhite;
    private javax.swing.JLabel lblAccountnumber;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblBarCode;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblInteres;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblcurrency;
    private javax.swing.JTable tblAccounHolder;
    private javax.swing.JTable tblTransactions;
    // End of variables declaration//GEN-END:variables
}
