/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itoson.lallorona.ui;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import mx.itoson.lallorona.entities.BankStatement;
import mx.itoson.lallorona.entities.Transaction;
import mx.itoson.lallorona.entities.AccountHolder;
/**
 * This class execute and display all the information contained on the json doc, showing all the data about the bank movements, their dates and other information
 * @author Vanni
 */
public class AccountLUI extends javax.swing.JFrame {

    /**
     * Creates new form AccountLUI
     */
    public AccountLUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProduct = new javax.swing.JLabel();
        btnSelectJson = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblBank = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAccountnumber = new javax.swing.JLabel();
        lblcurrency = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAccounHolder = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProduct.setBackground(new java.awt.Color(0, 102, 102));
        lblProduct.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblProduct.setForeground(new java.awt.Color(204, 204, 204));
        lblProduct.setText("...");

        btnSelectJson.setText("Select JSON");
        btnSelectJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectJsonActionPerformed(evt);
            }
        });

        tblTransactions.setBackground(new java.awt.Color(0, 102, 102));
        tblTransactions.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblTransactions.setForeground(new java.awt.Color(255, 255, 255));
        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Description", "Reference", "Amount", "Type"
            }
        ));
        tblTransactions.setGridColor(new java.awt.Color(102, 102, 102));
        tblTransactions.setSelectionForeground(new java.awt.Color(255, 51, 51));
        jScrollPane1.setViewportView(tblTransactions);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 33)); // NOI18N
        jLabel1.setText("DETALLE DE MOVIMIENTOS REALIZADOS  ");

        lblBank.setBackground(new java.awt.Color(255, 255, 255));
        lblBank.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        lblBank.setForeground(new java.awt.Color(0, 51, 204));
        lblBank.setText("BBVA");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        lblAccountnumber.setBackground(new java.awt.Color(0, 102, 102));
        lblAccountnumber.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        lblAccountnumber.setForeground(new java.awt.Color(153, 153, 153));
        lblAccountnumber.setText("...");

        lblcurrency.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblcurrency.setForeground(new java.awt.Color(153, 153, 153));
        lblcurrency.setText("...");

        tblAccounHolder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Accoun Holder"
            }
        ));
        jScrollPane2.setViewportView(tblAccounHolder);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAccountnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBank))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 821, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(btnSelectJson, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBank))
                .addGap(18, 18, 18)
                .addComponent(lblAccountnumber)
                .addGap(18, 18, 18)
                .addComponent(lblcurrency)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSelectJson, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * This metodod execute an action to select a doc made on json format and deserialize to a object
     * @param evt The action event generated by the button.
     */
    private void btnSelectJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectJsonActionPerformed
        FileDialog fileDialog = new FileDialog(this, "Select json file", FileDialog.LOAD);
        fileDialog.setVisible(true);
        
        String directory = fileDialog.getDirectory();
        String filename = fileDialog.getFile();
        
        if(filename != null){
            File selectedFile = new File(directory, filename);
        try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
            StringBuilder content = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                content.append(line).append("\n");
                }
            String contenido = content.toString();
            BankStatement a = BankStatement.deserialized(contenido);
            AccountHolder h = a.getAccountHolder();
            lblProduct.setText(a.getProduct());
            lblAccountnumber.setText("Account Number: " + a.getAccountNumber());
            lblcurrency.setText("Currency: " + a.getCurrency());
            DefaultTableModel m =(DefaultTableModel) tblAccounHolder.getModel();
            m.addRow(new Object[]{ "Code: " +           h.getCode() });
            m.addRow(new Object[]{ "Name: " +           h.getName() });
            m.addRow(new Object[]{ "Adress: " +        h.getAddress() });
            m.addRow(new Object[]{ "City: " +           h.getCity() });
            m.addRow(new Object[]{ "Taxpayer-id: " +              h.getTaxpayerId() });
            m.addRow(new Object[]{ "Zip code: "  +   h.getZipCode() });
            
            
            
            DefaultTableModel model =(DefaultTableModel) tblTransactions.getModel();
            model.setRowCount(0);
            List<Transaction> txs = new ArrayList<>( a.getTransactions() );
            txs.sort( Comparator.comparing(Transaction::getDate) );
            SimpleDateFormat dateFormat= new SimpleDateFormat("dd'/'MM'/'yyyy");// se puede cambiar el formato del año
            for (Transaction t : txs) {
            model.addRow(new Object[]{
                 dateFormat.format(t.getDate()),
                 t.getDescription(),
                 t.getReference(),
                 "$" + t.getAmount(),
                 t.getType(),                           
                            });                  
        }
 }
        catch (IOException ex) {
                        ex.printStackTrace();
                    }
        
    }      }//GEN-LAST:event_btnSelectJsonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountLUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountLUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountLUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountLUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountLUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectJson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAccountnumber;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblcurrency;
    private javax.swing.JTable tblAccounHolder;
    private javax.swing.JTable tblTransactions;
    // End of variables declaration//GEN-END:variables
}
