/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itoson.lallorona.ui;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import mx.itoson.lallorona.entities.BankStatement;
import mx.itoson.lallorona.entities.Transaction;

/**
 *
 * @author Vanni
 */
public class AccountLUI extends javax.swing.JFrame {

    /**
     * Creates new form AccountLUI
     */
    public AccountLUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProduct = new javax.swing.JLabel();
        btnSelectJson = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblBank = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProduct.setBackground(new java.awt.Color(0, 102, 102));
        lblProduct.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lblProduct.setForeground(new java.awt.Color(255, 255, 255));
        lblProduct.setText("...");

        btnSelectJson.setText("Select JSON");
        btnSelectJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectJsonActionPerformed(evt);
            }
        });

        tblTransactions.setBackground(new java.awt.Color(0, 102, 102));
        tblTransactions.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblTransactions.setForeground(new java.awt.Color(255, 255, 255));
        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date", "Description", "Reference", "Amount", "Type"
            }
        ));
        tblTransactions.setGridColor(new java.awt.Color(102, 102, 102));
        tblTransactions.setSelectionForeground(new java.awt.Color(255, 51, 51));
        jScrollPane1.setViewportView(tblTransactions);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 33)); // NOI18N
        jLabel1.setText("DETALLE DE MOVIMIENTOS REALIZADOS  ");

        lblBank.setBackground(new java.awt.Color(255, 255, 255));
        lblBank.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        lblBank.setForeground(new java.awt.Color(0, 51, 204));
        lblBank.setText("BBVA");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSelectJson, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblBank)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblBank)
                .addGap(7, 7, 7)
                .addComponent(lblProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(189, 189, 189)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSelectJson, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectJsonActionPerformed
 FileDialog fileDialog = new FileDialog(this, "Select json file", FileDialog.LOAD);
        fileDialog.setVisible(true);
        
        String directory = fileDialog.getDirectory();
        String filename = fileDialog.getFile();
        
        if(filename != null){
            File selectedFile = new File(directory, filename);
        try (BufferedReader reader = new BufferedReader(new FileReader(selectedFile))) {
            StringBuilder content = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                content.append(line).append("\n");
                }
            String contenido = content.toString();
            BankStatement a = BankStatement.deserialized(contenido);
            lblProduct.setText(a.getProduct());
                        
            DefaultTableModel model =(DefaultTableModel) tblTransactions.getModel();
            model.setRowCount(0);
            SimpleDateFormat dateFormat= new SimpleDateFormat("dd'/'MM'/'yyyy");// se puede cambiar el formato del año
         
                            for(Transaction t: a.getTransactions()){
                            model.addRow(new Object[]{
                                dateFormat.format(t.getDate()),
                                t.getDescription(),
                                t.getReference(),
                                "$" +t.getAmount(),
                                t.getType(),                            
                            });                  
        }
 }
        catch (IOException ex) {
                        ex.printStackTrace();
                    }
        
    }      }//GEN-LAST:event_btnSelectJsonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountLUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountLUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountLUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountLUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountLUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectJson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JTable tblTransactions;
    // End of variables declaration//GEN-END:variables
}
